# Generated by Django 5.0.6 on 2024-08-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_otp_customuser_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=254)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('password_changed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
